name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build plugin
        run: pnpm build

      - name: Create plugin zip
        run: |
          zip -r nostr-articles.zip main.js manifest.json styles.css

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nostr-articles.zip
          path: nostr-articles.zip

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            nostr-articles.zip main.js manifest.json styles.css
